const fs = require('fs');
const p = 'bundle.js';
let s = fs.readFileSync(p, 'utf8');

const replacement = `function Tp(e){let RECEIPT_LAYOUT_V10="double-size-detail";let t='<?xml version="1.0" encoding="utf-8"?><epos-print xmlns="http://www.epson-pos.com/schemas/2011/03/epos-print">';let n=e.total-e.total/1.10,r=x=>At(x),o=x=>(Number(x)||0).toFixed(2)+' EUR',b=' width="2" height="2"',l=()=>'<text font="font_b" width="2" height="2">---------------------</text><feed line="1"/>';t+='<text align="center" font="font_b" width="2" height="2">BEY-T</text><feed line="1"/>';t+='<text align="center" font="font_b" width="2" height="2">Traiteur Libanais</text><feed line="1"/>';t+='<text align="center" font="font_b" width="2" height="2">62 Av. Pierre Grenier</text><feed line="1"/>';t+='<text align="center" font="font_b" width="2" height="2">92100 Boulogne-Billancourt</text><feed line="1"/>';t+='<text align="center" font="font_b" width="2" height="2">SIRET 97961448400025</text><feed line="1"/>';t+=l();t+='<text align="center" font="font_b" width="2" height="2">Commande #'+r(e.num)+'</text><feed line="1"/>';t+='<text align="center" font="font_b" width="2" height="2">'+r((e.date||'')+'  '+(e.time||''))+'</text><feed line="1"/>';t+=l();t+='<text align="left" font="font_b" width="2" height="2">DETAIL DE LA COMMANDE</text><feed line="1"/>';e.items.forEach(a=>{t+='<text align="left" font="font_b" width="2" height="2">'+r(a.name)+'</text><feed line="1"/>';t+='<text align="left" font="font_b" width="2" height="2">'+r(a.qty+' x '+o(a.price)+' = '+o(a.qty*a.price))+'</text><feed line="1"/>';a.note&&(t+='<text align="left" font="font_b" width="2" height="2">'+r('> '+a.note)+'</text><feed line="1"/>')});e.discount>0&&(t+='<text align="right" font="font_b" width="2" height="2">'+r('Remise : -'+o(e.discount))+'</text><feed line="1"/>');t+=l();t+='<text align="center" font="font_b" width="2" height="2">TOTAL TTC '+r(o(e.total))+'</text><feed line="1"/>';t+='<text align="center" font="font_b" width="2" height="2">dont TVA 10% : '+r(o(n))+'</text><feed line="1"/>';t+='<text align="center" font="font_b" width="2" height="2">Paiement : '+r(e.paymentLabel.replace(/[^\\w\\s]/g,'').trim())+'</text><feed line="1"/>';if(e.paymentMode==='cash'&&e.cashGiven!=null){let a=Number(e.cashGiven)||0;t+='<text align="center" font="font_b" width="2" height="2">'+r('Recu : '+o(a))+'</text><feed line="1"/>';t+='<text align="center" font="font_b" width="2" height="2">'+r('Rendu : '+o(Math.max(0,a-e.total)))+'</text><feed line="1"/>'}t+=l();t+='<text align="center" font="font_b" width="2" height="2">Merci pour votre visite</text><feed line="1"/>';t+='<text align="center" font="font_b" width="2" height="2">A bientot chez Bey-T</text><feed line="1"/><cut type="feed"/></epos-print>';Pp(t)}function Np`;

const start = s.indexOf('function Tp(e){');
const end = s.indexOf('function Np(', start);
if (start < 0 || end < 0) throw new Error(`Tp/Np boundaries not found: start=${start}, end=${end}`);
s = s.slice(0, start) + replacement + s.slice(end + 'function Np'.length);

if (!s.includes('RECEIPT_LAYOUT_V10="double-size-detail"')) throw new Error('Receipt V10 marker missing after patch');
if (!s.includes('DETAIL DE LA COMMANDE')) throw new Error('Order detail heading missing after patch');
if (!s.includes('width="2" height="2"')) throw new Error('Double-size text attributes missing after patch');
fs.writeFileSync(p, s);
console.log('Patched receipt V10: 2x text size + full order detail');
